name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Le workflow est déclenché lorsqu'il y a un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Étape 2 : Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Choisir la version de Node.js à utiliser

      # Étape 3 : Installer les dépendances avec npm
      - name: Install dependencies
         run: cd mon_site_clean 
          npm install

      # Étape 4 : Installer Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Étape 5 : Authentification Firebase avec un token d'authentification (créé via `firebase login:ci`)
      - name: Authenticate to Firebase
        run: firebase use --add ${{ secrets.FIREBASE_TOKEN }}

      # Étape 6 : Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
